import type { TenantConfig } from '@/types/tenant'

export const lunarTenantConfig: TenantConfig = {
  id: 'tenant_lunar_001',
  slug: 'lunar',
  brandName: 'The Lunar Clothing',
  ownerName: 'Gowreesh KP',
  ownerEmail: 'gowreesh@thelunarclothing.com',
  ownerPhone: '+91 98765 43210',
  logo: '/lunar-logo.png',
  customDomain: 'www.thelunarclothing.com',
  status: 'active',
  plan: 'pro',
  createdAt: '2026-06-15',
  theme: {
    primaryColor: '#8C5A4F',
    accentColor: '#D4A574',
    backgroundColor: '#FAFAF8',
    fontDisplay: "'Instrument Serif', Georgia, serif",
    fontSans: "'Work Sans', system-ui, sans-serif",
    heroImage: 'https://cdn.shopify.com/s/files/1/0957/7549/0340/files/IMG_5227_1.jpg?v=1778607243',
    heroHeadline: 'Artisanal Elegance & Modern Heritage',
    heroSubhead: 'Handcrafted collections with pure breathable fabrics, master heritage craftsmanship, and functional luxury details.',
    heroCtaText: 'EXPLORE COLLECTIONS →',
    logoUrl: '/lunar-logo.png',
    announcementMessages: [
      'THE LUNAR CLOTHING • ELEGANT COTTON MAXIS & CHANDERI DRESSES',
      'FREE SHIPPING IN INDIA OVER ₹999',
      'USE CODE: LUNAR15 FOR 15% OFF YOUR ORDER',
      '100% PURE BREATHABLE COTTON • FUNCTIONAL POCKETS',
    ],
    enableAnimations: true,
    enableReviews: true,
    enableOrderTracking: true,
  },
  subscription: {
    plan: 'pro',
    pricePerMonth: 2499,
    status: 'active',
    nextBillingDate: '2026-10-15',
    paymentMethod: 'razorpay',
    invoices: [
      { id: 'INV-001', amount: 2499, status: 'paid', date: '2026-09-15', description: 'Pro Plan - September 2026' },
      { id: 'INV-002', amount: 2499, status: 'paid', date: '2026-08-15', description: 'Pro Plan - August 2026' },
      { id: 'INV-003', amount: 2499, status: 'paid', date: '2026-07-15', description: 'Pro Plan - July 2026' },
    ],
  },
  databaseConfig: {
    dbName: 'orvexa_tenant_lunar',
    mongoUri: 'mongodb://localhost:27017/orvexa_tenant_lunar',
    isolationMode: 'dedicated_database',
    folderPath: 'src/tenants/lunar',
  },
}
