// --- Seed Dataset for Master & Tenant Databases ---

export const SEED_TENANTS = [
  {
    id: 'tenant_lunar_001',
    slug: 'lunar',
    brandName: 'The Lunar Clothing',
    ownerName: 'Gowreesh KP',
    ownerEmail: 'gowreesh@thelunarclothing.com',
    ownerPhone: '+91 98765 43210',
    logo: '/lunar-logo.png',
    customDomain: 'www.thelunarclothing.com',
    status: 'active',
    plan: 'pro',
    createdAt: '2026-06-15',
    theme: {
      primaryColor: '#8C5A4F',
      accentColor: '#D4A574',
      backgroundColor: '#FAFAF8',
      fontDisplay: "'Instrument Serif', Georgia, serif",
      fontSans: "'Work Sans', system-ui, sans-serif",
      heroImage: 'https://cdn.shopify.com/s/files/1/0957/7549/0340/files/IMG_5227_1.jpg?v=1778607243',
      heroHeadline: 'Artisanal Elegance & Modern Heritage',
      heroSubhead: 'Handcrafted collections with pure breathable fabrics, master heritage craftsmanship, and functional luxury details.',
      heroCtaText: 'EXPLORE COLLECTIONS →',
      logoUrl: '/lunar-logo.png',
      announcementMessages: [
        'THE LUNAR CLOTHING • ELEGANT COTTON MAXIS & CHANDERI DRESSES',
        'FREE SHIPPING IN INDIA OVER ₹999',
        'USE CODE: LUNAR15 FOR 15% OFF YOUR ORDER',
        '100% PURE BREATHABLE COTTON • FUNCTIONAL POCKETS',
      ],
      enableAnimations: true,
      enableReviews: true,
      enableOrderTracking: true,
    },
    subscription: {
      plan: 'pro',
      pricePerMonth: 2499,
      status: 'active',
      nextBillingDate: '2026-10-15',
      paymentMethod: 'razorpay',
    },
  },
  {
    id: 'tenant_silkhaus_002',
    slug: 'silkhaus',
    brandName: 'Silk Haus',
    ownerName: 'Kavya Menon',
    ownerEmail: 'kavya@silkhaus.in',
    ownerPhone: '+91 87654 32109',
    logo: '',
    status: 'active',
    plan: 'starter',
    createdAt: '2026-08-02',
    theme: {
      primaryColor: '#1B2A4A',
      accentColor: '#C9A84C',
      backgroundColor: '#F8F6F0',
      fontDisplay: "'Playfair Display', Georgia, serif",
      fontSans: "'Inter', system-ui, sans-serif",
      heroImage: 'https://cdn.shopify.com/s/files/1/0957/7549/0340/files/IMG_5234.jpg?v=1778607246',
      heroHeadline: 'Royal Heritage Silks & Banarasi Splendor',
      heroSubhead: 'Woven with pure mulberry silk and handcrafted gold zari.',
      heroCtaText: 'DISCOVER SILKS →',
      logoUrl: '',
      announcementMessages: [
        'SILK HAUS • PREMIUM SILK SAREES & DUPATTAS',
        'FREE SHIPPING ALL INDIA • NO MINIMUM',
      ],
      enableAnimations: false,
      enableReviews: true,
      enableOrderTracking: false,
    },
    subscription: {
      plan: 'starter',
      pricePerMonth: 999,
      status: 'active',
      nextBillingDate: '2026-10-02',
      paymentMethod: 'razorpay',
    },
  },
]

export const SEED_APPLICATIONS = [
  {
    id: 'app_001',
    brandName: 'Bloom & Weave',
    ownerName: 'Pooja Sharma',
    ownerEmail: 'pooja@bloomweave.com',
    ownerPhone: '+91 99887 76655',
    category: 'Sustainable Linen & Handloom',
    requestedSubdomain: 'bloomweave',
    description: 'We are a boutique slow-fashion brand looking to launch our online storefront.',
    submittedAt: '2026-09-12',
    status: 'pending' as const,
  },
  {
    id: 'app_002',
    brandName: 'Khadi Studio',
    ownerName: 'Arjun Patel',
    ownerEmail: 'arjun@khadistudio.co',
    ownerPhone: '+91 76543 21098',
    category: 'Handspun Khadi Fashion',
    requestedSubdomain: 'khadistudio',
    description: 'Organic handspun garments crafted by rural artisan cooperatives.',
    submittedAt: '2026-09-10',
    status: 'pending' as const,
  },
]

export const SEED_LUNAR_PRODUCTS = [
  {
    id: 1,
    name: 'Midnight Chanderi Silk Tiered Maxi Dress',
    category: 'maxis',
    price: 1899,
    priceFormatted: '₹1,899',
    originalPrice: 2499,
    sculptLevel: 'A-LINE FLARE',
    badge: 'BESTSELLER',
    fabricTech: 'Pure Chanderi Silk + Mulmul Lining',
    fabricDesc: 'Featherweight breathable Chanderi silk with a natural luminous sheen.',
    compression: 'A-LINE FLARE',
    desc: 'An enchanting tiered silhouette handcrafted with authentic Chanderi silk and gold zari accents.',
    details: [
      'Deep side utility pocket for phone & essentials',
      'Attached adjustable side waist tie-up ropes',
      'Concealed feeding zips available upon request',
    ],
    fitInfo: 'True to size with adjustable attached side tie-up ropes.',
    rating: 4.9,
    reviewsCount: 38,
    imgMain: 'https://cdn.shopify.com/s/files/1/0957/7549/0340/files/IMG_5227_1.jpg?v=1778607243',
    images: ['https://cdn.shopify.com/s/files/1/0957/7549/0340/files/IMG_5227_1.jpg?v=1778607243'],
    colors: [{ name: 'Indigo Black', hex: '#222222' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: 45,
    featured: true,
  },
]
